### ISSUE TITLE
Virtual device on minSdkVersion: adding one and testing the app

### ISSUE THREAD

**Issue by ARNdroid** [ARNdroid/EasyTargetDiet#140]
TODO
- Create a virtual device (on Mamute + Mac) targeting our minSdkVersion;
- Execute debug test of ALL features;
- Document the need to execute tests in this device before a new release rollout.

**Comment by gmale** [comment]
Just a friendly FYI: this crash is a known Android issue when using emulators with API 15 and should be addressed soon. In the meantime, the workaround is to turn off the `Use Host GPU` option on the emulator. [See more info here](https://code.google.com/p/android/issues/detail?id=77759).

**Comment by ARNdroid** [comment]
@gmale Thanks!!!
