### ISSUE TITLE
Build: add message at end of assemble (release?)

### ISSUE THREAD

**Issue by ARNdroid** [ARNdroid/EasyTargetDiet#216]
The message may be:

```
==========================================
              BUILD SUMMARY
------------------------------------------
Module       :  etd-app
Version name :  0.11.0
Version code :  11000
Throwable    :  NONE
==========================================
```

**Comment by alceurneto** [comment]
Some topics that could help us:
- <a href="http://gradle.org/docs/current/userguide/build_lifecycle.html">Gradle User Guide: The Build Lifecycle</a>;
- <a href="http://stackoverflow.com/questions/23867318/is-there-a-method-in-gradle-to-execute-some-task-after-the-build">Related question at Stackoverflow</a>.
